{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0dbde6a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import gzip\n",
    "import json\n",
    "import os\n",
    "import pandas as pd\n",
    "import requests\n",
    "\n",
    "from io import BytesIO\n",
    "from time import sleep"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c4806ca7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading details for movie\n",
      "Finished downloading 100 entries for movie\n",
      "Finished downloading 200 entries for movie\n",
      "Finished downloading 300 entries for movie\n",
      "Finished downloading 400 entries for movie\n",
      "Finished downloading 500 entries for movie\n",
      "Finished downloading 600 entries for movie\n",
      "Finished downloading 700 entries for movie\n",
      "Finished downloading 800 entries for movie\n",
      "Finished downloading 900 entries for movie\n",
      "Finished downloading 1000 entries for movie\n",
      "Finished downloading 1100 entries for movie\n",
      "Finished downloading 1200 entries for movie\n",
      "Finished downloading 1300 entries for movie\n",
      "Finished downloading 1400 entries for movie\n",
      "Finished downloading 1500 entries for movie\n",
      "Finished downloading 1600 entries for movie\n",
      "Finished downloading 1700 entries for movie\n",
      "Finished downloading 1800 entries for movie\n",
      "Finished downloading 1900 entries for movie\n",
      "Finished downloading 2000 entries for movie\n",
      "Finished downloading 2100 entries for movie\n",
      "Finished downloading 2200 entries for movie\n",
      "Finished downloading 2300 entries for movie\n",
      "Finished downloading 2400 entries for movie\n",
      "Finished downloading 2500 entries for movie\n",
      "Finished downloading 2600 entries for movie\n",
      "Finished downloading 2700 entries for movie\n",
      "Finished downloading 2800 entries for movie\n",
      "Finished downloading 2900 entries for movie\n",
      "Finished downloading 3000 entries for movie\n",
      "Finished downloading 3100 entries for movie\n",
      "Finished downloading 3200 entries for movie\n",
      "Finished downloading 3300 entries for movie\n",
      "Finished downloading 3400 entries for movie\n",
      "Finished downloading 3500 entries for movie\n",
      "Finished downloading 3600 entries for movie\n",
      "Finished downloading 3700 entries for movie\n",
      "Finished downloading 3800 entries for movie\n",
      "Finished downloading 3900 entries for movie\n",
      "Finished downloading 4000 entries for movie\n",
      "Finished downloading 4100 entries for movie\n",
      "Finished downloading 4200 entries for movie\n",
      "Finished downloading 4300 entries for movie\n",
      "Finished downloading 4400 entries for movie\n",
      "Finished downloading 4500 entries for movie\n",
      "Finished downloading 4600 entries for movie\n",
      "Finished downloading 4700 entries for movie\n",
      "Finished downloading 4800 entries for movie\n",
      "Finished downloading 4900 entries for movie\n",
      "Finished downloading 5000 entries for movie\n",
      "Finished downloading 5100 entries for movie\n",
      "Finished downloading 5200 entries for movie\n",
      "Finished downloading 5300 entries for movie\n",
      "Finished downloading 5400 entries for movie\n",
      "Finished downloading 5500 entries for movie\n",
      "Finished downloading 5600 entries for movie\n",
      "Finished downloading 5700 entries for movie\n",
      "Finished downloading 5800 entries for movie\n",
      "Finished downloading 5900 entries for movie\n",
      "Finished downloading 6000 entries for movie\n",
      "Finished downloading 6100 entries for movie\n",
      "Finished downloading 6200 entries for movie\n",
      "Finished downloading 6300 entries for movie\n",
      "Finished downloading 6400 entries for movie\n",
      "Finished downloading 6500 entries for movie\n",
      "Finished downloading 6600 entries for movie\n",
      "Finished downloading 6700 entries for movie\n",
      "Finished downloading 6800 entries for movie\n",
      "Finished downloading 6900 entries for movie\n",
      "Finished downloading 7000 entries for movie\n",
      "Finished downloading 7100 entries for movie\n",
      "Finished downloading 7200 entries for movie\n",
      "Finished downloading 7300 entries for movie\n",
      "Finished downloading 7400 entries for movie\n",
      "Finished downloading 7500 entries for movie\n",
      "Finished downloading 7600 entries for movie\n",
      "Finished downloading 7700 entries for movie\n",
      "Finished downloading 7800 entries for movie\n",
      "Finished downloading 7900 entries for movie\n",
      "Finished downloading 8000 entries for movie\n",
      "Finished downloading 8100 entries for movie\n",
      "Finished downloading 8200 entries for movie\n",
      "Finished downloading 8300 entries for movie\n",
      "Finished downloading 8400 entries for movie\n",
      "Finished downloading 8500 entries for movie\n",
      "Finished downloading 8600 entries for movie\n",
      "Finished downloading 8700 entries for movie\n",
      "Finished downloading 8800 entries for movie\n",
      "Finished downloading 8900 entries for movie\n",
      "Finished downloading 9000 entries for movie\n",
      "Finished downloading 9100 entries for movie\n",
      "Finished downloading 9200 entries for movie\n",
      "Finished downloading 9300 entries for movie\n",
      "Finished downloading 9400 entries for movie\n",
      "Finished downloading 9500 entries for movie\n",
      "Finished downloading 9600 entries for movie\n",
      "Finished downloading 9700 entries for movie\n",
      "Finished downloading 9800 entries for movie\n",
      "Finished downloading 9900 entries for movie\n",
      "Finished downloading 10000 entries for movie\n",
      "Finished downloading 10100 entries for movie\n",
      "Finished downloading 10200 entries for movie\n",
      "Finished downloading 10300 entries for movie\n",
      "Finished downloading 10400 entries for movie\n",
      "Finished downloading 10500 entries for movie\n",
      "Finished downloading 10600 entries for movie\n",
      "Finished downloading 10700 entries for movie\n",
      "Finished downloading 10800 entries for movie\n",
      "Finished downloading 10900 entries for movie\n",
      "Finished downloading 11000 entries for movie\n",
      "Finished downloading 11100 entries for movie\n",
      "Finished downloading 11200 entries for movie\n",
      "Finished downloading 11300 entries for movie\n",
      "Finished downloading 11400 entries for movie\n",
      "Finished downloading 11500 entries for movie\n",
      "Finished downloading 11600 entries for movie\n",
      "Finished downloading 11700 entries for movie\n",
      "Finished downloading 11800 entries for movie\n",
      "Finished downloading 11900 entries for movie\n",
      "Finished downloading 12000 entries for movie\n",
      "Finished downloading 12100 entries for movie\n",
      "Finished downloading 12200 entries for movie\n",
      "Finished downloading 12300 entries for movie\n",
      "Finished downloading 12400 entries for movie\n",
      "Finished downloading 12500 entries for movie\n",
      "Finished downloading 12600 entries for movie\n",
      "Finished downloading 12700 entries for movie\n",
      "Finished downloading 12800 entries for movie\n",
      "Finished downloading 12900 entries for movie\n",
      "Finished downloading 13000 entries for movie\n",
      "Finished downloading 13100 entries for movie\n",
      "Finished downloading 13200 entries for movie\n",
      "Finished downloading 13300 entries for movie\n",
      "Finished downloading 13400 entries for movie\n",
      "Finished downloading 13500 entries for movie\n",
      "Finished downloading 13600 entries for movie\n",
      "Finished downloading 13700 entries for movie\n",
      "Finished downloading 13800 entries for movie\n",
      "Finished downloading 13900 entries for movie\n",
      "Finished downloading 14000 entries for movie\n",
      "Finished downloading 14100 entries for movie\n",
      "Finished downloading 14200 entries for movie\n",
      "Finished downloading 14300 entries for movie\n",
      "Finished downloading 14400 entries for movie\n",
      "Finished downloading 14500 entries for movie\n",
      "Finished downloading 14600 entries for movie\n",
      "Finished downloading 14700 entries for movie\n",
      "Finished downloading 14800 entries for movie\n",
      "Finished downloading 14900 entries for movie\n",
      "Finished downloading 15000 entries for movie\n",
      "Finished downloading 15100 entries for movie\n",
      "Finished downloading 15200 entries for movie\n",
      "Finished downloading 15300 entries for movie\n",
      "Finished downloading 15400 entries for movie\n",
      "Finished downloading 15500 entries for movie\n",
      "Finished downloading 15600 entries for movie\n",
      "Finished downloading 15700 entries for movie\n",
      "Finished downloading 15800 entries for movie\n",
      "Finished downloading 15900 entries for movie\n",
      "Finished downloading 16000 entries for movie\n",
      "Finished downloading 16100 entries for movie\n",
      "Finished downloading 16200 entries for movie\n",
      "Finished downloading 16300 entries for movie\n",
      "Finished downloading 16400 entries for movie\n",
      "Finished downloading 16500 entries for movie\n",
      "Finished downloading 16600 entries for movie\n",
      "Finished downloading 16700 entries for movie\n",
      "Finished downloading 16800 entries for movie\n",
      "Finished downloading 16900 entries for movie\n",
      "Finished downloading 17000 entries for movie\n",
      "Finished downloading 17100 entries for movie\n",
      "Finished downloading 17200 entries for movie\n",
      "Finished downloading 17300 entries for movie\n",
      "Finished downloading 17400 entries for movie\n",
      "Finished downloading 17500 entries for movie\n",
      "Finished downloading 17600 entries for movie\n",
      "Finished downloading 17700 entries for movie\n",
      "Finished downloading 17800 entries for movie\n",
      "Finished downloading 17900 entries for movie\n",
      "Finished downloading 18000 entries for movie\n",
      "Finished downloading 18100 entries for movie\n",
      "Finished downloading 18200 entries for movie\n",
      "Finished downloading 18300 entries for movie\n",
      "Finished downloading 18400 entries for movie\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished downloading 18500 entries for movie\n",
      "Finished downloading 18600 entries for movie\n",
      "Finished downloading 18700 entries for movie\n",
      "Finished downloading 18800 entries for movie\n",
      "Finished downloading 18900 entries for movie\n",
      "Finished downloading 19000 entries for movie\n",
      "Finished downloading 19100 entries for movie\n",
      "Finished downloading 19200 entries for movie\n",
      "Finished downloading 19300 entries for movie\n",
      "Finished downloading 19400 entries for movie\n",
      "Finished downloading 19500 entries for movie\n",
      "Finished downloading 19600 entries for movie\n",
      "Finished downloading 19700 entries for movie\n",
      "Finished downloading 19800 entries for movie\n",
      "Finished downloading 19900 entries for movie\n",
      "Finished downloading 20000 entries for movie\n",
      "Finished downloading 20100 entries for movie\n",
      "Finished downloading 20200 entries for movie\n",
      "Finished downloading 20300 entries for movie\n",
      "Finished downloading 20400 entries for movie\n",
      "Finished downloading 20500 entries for movie\n",
      "Finished downloading 20600 entries for movie\n",
      "Finished downloading 20700 entries for movie\n",
      "Finished downloading 20800 entries for movie\n",
      "Finished downloading 20900 entries for movie\n",
      "Finished downloading 21000 entries for movie\n",
      "Finished downloading 21100 entries for movie\n",
      "Finished downloading 21200 entries for movie\n",
      "Finished downloading 21300 entries for movie\n",
      "Finished downloading 21400 entries for movie\n",
      "Finished downloading 21500 entries for movie\n",
      "Finished downloading 21600 entries for movie\n",
      "Finished downloading 21700 entries for movie\n",
      "Finished downloading 21800 entries for movie\n",
      "Finished downloading 21900 entries for movie\n",
      "Finished downloading 22000 entries for movie\n",
      "Finished downloading 22100 entries for movie\n",
      "Finished downloading 22200 entries for movie\n",
      "Finished downloading 22300 entries for movie\n",
      "Finished downloading 22400 entries for movie\n",
      "Finished downloading 22500 entries for movie\n",
      "Finished downloading 22600 entries for movie\n",
      "Finished downloading 22700 entries for movie\n",
      "Finished downloading 22800 entries for movie\n",
      "Finished downloading 22900 entries for movie\n",
      "Finished downloading 23000 entries for movie\n",
      "Finished downloading 23100 entries for movie\n",
      "Finished downloading 23200 entries for movie\n",
      "Finished downloading 23300 entries for movie\n",
      "Finished downloading 23400 entries for movie\n",
      "Finished downloading 23500 entries for movie\n",
      "Finished downloading 23600 entries for movie\n",
      "Finished downloading 23700 entries for movie\n",
      "Finished downloading 23800 entries for movie\n",
      "Finished downloading 23900 entries for movie\n",
      "Finished downloading 24000 entries for movie\n",
      "Finished downloading 24100 entries for movie\n",
      "Finished downloading 24200 entries for movie\n",
      "Finished downloading 24300 entries for movie\n",
      "Finished downloading 24400 entries for movie\n",
      "Finished downloading 24500 entries for movie\n",
      "Finished downloading 24600 entries for movie\n",
      "Finished downloading 24700 entries for movie\n",
      "Finished downloading 24800 entries for movie\n",
      "Finished downloading 24900 entries for movie\n",
      "Finished downloading 25000 entries for movie\n",
      "Finished downloading 25100 entries for movie\n",
      "Finished downloading 25200 entries for movie\n",
      "Finished downloading 25300 entries for movie\n",
      "Finished downloading 25400 entries for movie\n",
      "Finished downloading 25500 entries for movie\n",
      "Finished downloading 25600 entries for movie\n",
      "Finished downloading 25700 entries for movie\n",
      "Finished downloading 25800 entries for movie\n",
      "Finished downloading 25900 entries for movie\n",
      "Finished downloading 26000 entries for movie\n",
      "Finished downloading 26100 entries for movie\n",
      "Finished downloading 26200 entries for movie\n",
      "Finished downloading 26300 entries for movie\n",
      "Finished downloading 26400 entries for movie\n",
      "Finished downloading 26500 entries for movie\n",
      "Finished downloading 26600 entries for movie\n",
      "Finished downloading 26700 entries for movie\n",
      "Finished downloading 26800 entries for movie\n",
      "Finished downloading 26900 entries for movie\n",
      "Finished downloading 27000 entries for movie\n",
      "Finished downloading 27100 entries for movie\n",
      "Finished downloading 27200 entries for movie\n",
      "Finished downloading 27300 entries for movie\n",
      "Finished downloading 27400 entries for movie\n",
      "Finished downloading 27500 entries for movie\n",
      "Finished downloading 27600 entries for movie\n",
      "Finished downloading 27700 entries for movie\n",
      "Finished downloading 27800 entries for movie\n",
      "Finished downloading 27900 entries for movie\n",
      "Finished downloading 28000 entries for movie\n",
      "Finished downloading 28100 entries for movie\n",
      "Finished downloading 28200 entries for movie\n",
      "Finished downloading 28300 entries for movie\n",
      "Finished downloading 28400 entries for movie\n",
      "Finished downloading 28500 entries for movie\n",
      "Finished downloading 28600 entries for movie\n",
      "Finished downloading 28700 entries for movie\n",
      "Finished downloading 28800 entries for movie\n",
      "Finished downloading 28900 entries for movie\n",
      "Finished downloading 29000 entries for movie\n",
      "Finished downloading 29100 entries for movie\n",
      "Finished downloading 29200 entries for movie\n",
      "Finished downloading 29300 entries for movie\n",
      "Finished downloading 29400 entries for movie\n",
      "Finished downloading 29500 entries for movie\n",
      "Finished downloading 29600 entries for movie\n",
      "Finished downloading 29700 entries for movie\n",
      "Finished downloading 29800 entries for movie\n",
      "Finished downloading 29900 entries for movie\n",
      "Finished downloading 30000 entries for movie\n",
      "Finished downloading 30100 entries for movie\n",
      "Finished downloading 30200 entries for movie\n",
      "Finished downloading 30300 entries for movie\n",
      "Finished downloading 30400 entries for movie\n",
      "Finished downloading 30500 entries for movie\n",
      "Finished downloading 30600 entries for movie\n",
      "Finished downloading 30700 entries for movie\n",
      "Finished downloading 30800 entries for movie\n",
      "Finished downloading 30900 entries for movie\n",
      "Finished downloading 31000 entries for movie\n",
      "Finished downloading 31100 entries for movie\n",
      "Finished downloading 31200 entries for movie\n",
      "Finished downloading 31300 entries for movie\n",
      "Finished downloading 31400 entries for movie\n",
      "Finished downloading 31500 entries for movie\n",
      "Finished downloading 31600 entries for movie\n",
      "Finished downloading 31700 entries for movie\n",
      "Finished downloading 31800 entries for movie\n",
      "Finished downloading 31900 entries for movie\n",
      "Finished downloading 32000 entries for movie\n",
      "Finished downloading 32100 entries for movie\n",
      "Finished downloading 32200 entries for movie\n",
      "Finished downloading 32300 entries for movie\n",
      "Finished downloading 32400 entries for movie\n",
      "Finished downloading 32500 entries for movie\n",
      "Finished downloading 32600 entries for movie\n",
      "Finished downloading 32700 entries for movie\n",
      "Finished downloading 32800 entries for movie\n",
      "Finished downloading 32900 entries for movie\n",
      "Finished downloading 33000 entries for movie\n",
      "Finished downloading 33100 entries for movie\n",
      "Finished downloading 33200 entries for movie\n",
      "Finished downloading 33300 entries for movie\n",
      "Finished downloading 33400 entries for movie\n",
      "Finished downloading 33500 entries for movie\n",
      "Finished downloading 33600 entries for movie\n",
      "Finished downloading 33700 entries for movie\n",
      "Finished downloading 33800 entries for movie\n",
      "Finished downloading 33900 entries for movie\n",
      "Finished downloading 34000 entries for movie\n",
      "Finished downloading 34100 entries for movie\n",
      "Finished downloading 34200 entries for movie\n",
      "Finished downloading 34300 entries for movie\n",
      "Finished downloading 34400 entries for movie\n",
      "Finished downloading 34500 entries for movie\n",
      "Finished downloading 34600 entries for movie\n",
      "Finished downloading 34700 entries for movie\n",
      "Finished downloading 34800 entries for movie\n",
      "Finished downloading 34900 entries for movie\n",
      "Finished downloading 35000 entries for movie\n",
      "Finished downloading 35100 entries for movie\n",
      "Finished downloading 35200 entries for movie\n",
      "Finished downloading 35300 entries for movie\n",
      "Finished downloading 35400 entries for movie\n",
      "Finished downloading 35500 entries for movie\n",
      "Finished downloading 35600 entries for movie\n",
      "Finished downloading 35700 entries for movie\n",
      "Finished downloading 35800 entries for movie\n",
      "Finished downloading 35900 entries for movie\n",
      "Finished downloading 36000 entries for movie\n",
      "Finished downloading 36100 entries for movie\n",
      "Finished downloading 36200 entries for movie\n",
      "Finished downloading 36300 entries for movie\n",
      "Finished downloading 36400 entries for movie\n",
      "Finished downloading 36500 entries for movie\n",
      "Finished downloading 36600 entries for movie\n",
      "Finished downloading 36700 entries for movie\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished downloading 36800 entries for movie\n",
      "Finished downloading 36900 entries for movie\n",
      "Finished downloading 37000 entries for movie\n",
      "Finished downloading 37100 entries for movie\n",
      "Finished downloading 37200 entries for movie\n",
      "Finished downloading 37300 entries for movie\n",
      "Finished downloading 37400 entries for movie\n",
      "Finished downloading 37500 entries for movie\n",
      "Finished downloading 37600 entries for movie\n",
      "Finished downloading 37700 entries for movie\n",
      "Finished downloading 37800 entries for movie\n",
      "Finished downloading 37900 entries for movie\n",
      "Finished downloading 38000 entries for movie\n",
      "Finished downloading 38100 entries for movie\n",
      "Finished downloading 38200 entries for movie\n",
      "Finished downloading 38300 entries for movie\n",
      "Finished downloading 38400 entries for movie\n",
      "Finished downloading 38500 entries for movie\n",
      "Finished downloading 38600 entries for movie\n",
      "Finished downloading 38700 entries for movie\n",
      "Finished downloading 38800 entries for movie\n",
      "Finished downloading 38900 entries for movie\n",
      "Finished downloading 39000 entries for movie\n",
      "Finished downloading 39100 entries for movie\n",
      "Finished downloading 39200 entries for movie\n",
      "Finished downloading 39300 entries for movie\n",
      "Finished downloading 39400 entries for movie\n",
      "Finished downloading 39500 entries for movie\n",
      "Finished downloading 39600 entries for movie\n",
      "Finished downloading 39700 entries for movie\n",
      "Finished downloading 39800 entries for movie\n",
      "Finished downloading 39900 entries for movie\n",
      "Finished downloading 40000 entries for movie\n",
      "Finished downloading 40100 entries for movie\n",
      "Finished downloading 40200 entries for movie\n",
      "Finished downloading 40300 entries for movie\n",
      "Finished downloading 40400 entries for movie\n",
      "Finished downloading 40500 entries for movie\n",
      "Finished downloading 40600 entries for movie\n",
      "Finished downloading 40700 entries for movie\n",
      "Finished downloading 40800 entries for movie\n",
      "Finished downloading 40900 entries for movie\n",
      "Finished downloading 41000 entries for movie\n",
      "Finished downloading 41100 entries for movie\n",
      "Finished downloading 41200 entries for movie\n",
      "Finished downloading 41300 entries for movie\n",
      "Finished downloading 41400 entries for movie\n",
      "Finished downloading 41500 entries for movie\n",
      "Finished downloading 41600 entries for movie\n",
      "Finished downloading 41700 entries for movie\n",
      "Finished downloading 41800 entries for movie\n",
      "Finished downloading 41900 entries for movie\n",
      "Finished downloading 42000 entries for movie\n",
      "Finished downloading 42100 entries for movie\n",
      "Finished downloading 42200 entries for movie\n",
      "Finished downloading 42300 entries for movie\n",
      "Finished downloading 42400 entries for movie\n",
      "Finished downloading 42500 entries for movie\n",
      "Finished downloading 42600 entries for movie\n",
      "Finished downloading 42700 entries for movie\n",
      "Finished downloading 42800 entries for movie\n",
      "Finished downloading 42900 entries for movie\n",
      "Finished downloading 43000 entries for movie\n",
      "Finished downloading 43100 entries for movie\n",
      "Finished downloading 43200 entries for movie\n",
      "Finished downloading 43300 entries for movie\n",
      "Finished downloading 43400 entries for movie\n",
      "Finished downloading 43500 entries for movie\n",
      "Finished downloading 43600 entries for movie\n",
      "Finished downloading 43700 entries for movie\n",
      "Finished downloading 43800 entries for movie\n",
      "Finished downloading 43900 entries for movie\n",
      "Finished downloading 44000 entries for movie\n",
      "Finished downloading 44100 entries for movie\n",
      "Finished downloading 44200 entries for movie\n",
      "Finished downloading 44300 entries for movie\n",
      "Finished downloading 44400 entries for movie\n",
      "Finished downloading 44500 entries for movie\n",
      "Finished downloading 44600 entries for movie\n",
      "Finished downloading 44700 entries for movie\n",
      "Finished downloading 44800 entries for movie\n",
      "Finished downloading 44900 entries for movie\n",
      "Finished downloading 45000 entries for movie\n",
      "Finished downloading 45100 entries for movie\n",
      "Finished downloading 45200 entries for movie\n",
      "Finished downloading 45300 entries for movie\n",
      "Finished downloading 45400 entries for movie\n",
      "Finished downloading 45500 entries for movie\n",
      "Finished downloading 45600 entries for movie\n",
      "Finished downloading 45700 entries for movie\n",
      "Finished downloading 45800 entries for movie\n",
      "Finished downloading 45900 entries for movie\n",
      "Finished downloading 46000 entries for movie\n",
      "Finished downloading 46100 entries for movie\n",
      "Finished downloading 46200 entries for movie\n",
      "Finished downloading 46300 entries for movie\n",
      "Finished downloading 46400 entries for movie\n",
      "Finished downloading 46500 entries for movie\n",
      "Finished downloading 46600 entries for movie\n",
      "Finished downloading 46700 entries for movie\n",
      "Finished downloading 46800 entries for movie\n",
      "Finished downloading 46900 entries for movie\n",
      "Finished downloading 47000 entries for movie\n",
      "Finished downloading 47100 entries for movie\n",
      "Finished downloading 47200 entries for movie\n",
      "Finished downloading 47300 entries for movie\n",
      "Finished downloading 47400 entries for movie\n",
      "Finished downloading 47500 entries for movie\n",
      "Finished downloading 47600 entries for movie\n",
      "Finished downloading 47700 entries for movie\n",
      "Finished downloading 47800 entries for movie\n",
      "Finished downloading 47900 entries for movie\n",
      "Finished downloading 48000 entries for movie\n",
      "Finished downloading 48100 entries for movie\n",
      "Finished downloading 48200 entries for movie\n",
      "Finished downloading 48300 entries for movie\n",
      "Finished downloading 48400 entries for movie\n",
      "Finished downloading 48500 entries for movie\n",
      "Finished downloading 48600 entries for movie\n",
      "Finished downloading 48700 entries for movie\n",
      "Finished downloading 48800 entries for movie\n",
      "Finished downloading 48900 entries for movie\n",
      "Finished downloading 49000 entries for movie\n",
      "Finished downloading 49100 entries for movie\n",
      "Finished downloading 49200 entries for movie\n",
      "Finished downloading 49300 entries for movie\n",
      "Finished downloading 49400 entries for movie\n",
      "Finished downloading 49500 entries for movie\n",
      "Finished downloading 49600 entries for movie\n",
      "Finished downloading 49700 entries for movie\n",
      "Finished downloading 49800 entries for movie\n",
      "Finished downloading 49900 entries for movie\n",
      "Finished downloading 50000 entries for movie\n",
      "Finished downloading 50100 entries for movie\n",
      "Finished downloading 50200 entries for movie\n",
      "Finished downloading 50300 entries for movie\n",
      "Finished downloading 50400 entries for movie\n",
      "Finished downloading 50500 entries for movie\n",
      "Finished downloading 50600 entries for movie\n",
      "Finished downloading 50700 entries for movie\n",
      "Finished downloading 50800 entries for movie\n",
      "Finished downloading 50900 entries for movie\n",
      "Finished downloading 51000 entries for movie\n",
      "Finished downloading 51100 entries for movie\n",
      "Finished downloading 51200 entries for movie\n",
      "Finished downloading 51300 entries for movie\n",
      "Finished downloading 51400 entries for movie\n",
      "Finished downloading 51500 entries for movie\n",
      "Finished downloading 51600 entries for movie\n",
      "Finished downloading 51700 entries for movie\n",
      "Finished downloading 51800 entries for movie\n",
      "Finished downloading 51900 entries for movie\n",
      "Finished downloading 52000 entries for movie\n",
      "Finished downloading 52100 entries for movie\n",
      "Finished downloading 52200 entries for movie\n",
      "Finished downloading 52300 entries for movie\n",
      "Finished downloading 52400 entries for movie\n",
      "Finished downloading 52500 entries for movie\n",
      "Finished downloading 52600 entries for movie\n",
      "Finished downloading 52700 entries for movie\n",
      "Finished downloading 52800 entries for movie\n",
      "Finished downloading 52900 entries for movie\n",
      "Finished downloading 53000 entries for movie\n",
      "Finished downloading 53100 entries for movie\n",
      "Finished downloading 53200 entries for movie\n",
      "Finished downloading 53300 entries for movie\n",
      "Finished downloading 53400 entries for movie\n",
      "Finished downloading 53500 entries for movie\n",
      "Finished downloading 53600 entries for movie\n",
      "Finished downloading 53700 entries for movie\n",
      "Finished downloading 53800 entries for movie\n",
      "Finished downloading 53900 entries for movie\n",
      "Finished downloading 54000 entries for movie\n",
      "Finished downloading 54100 entries for movie\n",
      "Finished downloading 54200 entries for movie\n",
      "Finished downloading 54300 entries for movie\n",
      "Finished downloading 54400 entries for movie\n",
      "Finished downloading 54500 entries for movie\n",
      "Finished downloading 54600 entries for movie\n",
      "Finished downloading 54700 entries for movie\n",
      "Finished downloading 54800 entries for movie\n",
      "Finished downloading 54900 entries for movie\n",
      "Finished downloading 55000 entries for movie\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished downloading 55100 entries for movie\n",
      "Finished downloading 55200 entries for movie\n",
      "Finished downloading 55300 entries for movie\n",
      "Finished downloading 55400 entries for movie\n",
      "Finished downloading 55500 entries for movie\n",
      "Finished downloading 55600 entries for movie\n",
      "Finished downloading 55700 entries for movie\n",
      "Finished downloading 55800 entries for movie\n",
      "Finished downloading 55900 entries for movie\n",
      "Finished downloading 56000 entries for movie\n",
      "Finished downloading 56100 entries for movie\n",
      "Finished downloading 56200 entries for movie\n",
      "Finished downloading 56300 entries for movie\n",
      "Finished downloading 56400 entries for movie\n",
      "Finished downloading 56500 entries for movie\n",
      "Finished downloading 56600 entries for movie\n",
      "Finished downloading 56700 entries for movie\n",
      "Finished downloading 56800 entries for movie\n",
      "Finished downloading 56900 entries for movie\n",
      "Finished downloading 57000 entries for movie\n",
      "Finished downloading 57100 entries for movie\n",
      "Finished downloading 57200 entries for movie\n",
      "Finished downloading 57300 entries for movie\n",
      "Finished downloading 57400 entries for movie\n",
      "Finished downloading 57500 entries for movie\n",
      "Finished downloading 57600 entries for movie\n",
      "Finished downloading 57700 entries for movie\n",
      "Finished downloading 57800 entries for movie\n",
      "Finished downloading 57900 entries for movie\n",
      "Finished downloading 58000 entries for movie\n",
      "Finished downloading 58100 entries for movie\n",
      "Finished downloading 58200 entries for movie\n",
      "Finished downloading 58300 entries for movie\n",
      "Finished downloading 58400 entries for movie\n",
      "Finished downloading 58500 entries for movie\n",
      "Finished downloading 58600 entries for movie\n",
      "Finished downloading 58700 entries for movie\n",
      "Finished downloading 58800 entries for movie\n",
      "Finished downloading 58900 entries for movie\n",
      "Finished downloading 59000 entries for movie\n",
      "Finished downloading 59100 entries for movie\n",
      "Finished downloading 59200 entries for movie\n",
      "Finished downloading 59300 entries for movie\n",
      "Finished downloading 59400 entries for movie\n",
      "Finished downloading 59500 entries for movie\n",
      "Finished downloading 59600 entries for movie\n",
      "Finished downloading 59700 entries for movie\n",
      "Finished downloading 59800 entries for movie\n",
      "Finished downloading 59900 entries for movie\n",
      "Finished downloading 60000 entries for movie\n",
      "Finished downloading 60100 entries for movie\n",
      "Finished downloading 60200 entries for movie\n",
      "Finished downloading 60300 entries for movie\n",
      "Finished downloading 60400 entries for movie\n",
      "Finished downloading 60500 entries for movie\n",
      "Finished downloading 60600 entries for movie\n",
      "Failed on id # 84916\n",
      "Finished downloading 60700 entries for movie\n",
      "Finished downloading 60800 entries for movie\n",
      "Finished downloading 60900 entries for movie\n",
      "Finished downloading 61000 entries for movie\n",
      "Finished downloading 61100 entries for movie\n",
      "Finished downloading 61200 entries for movie\n",
      "Finished downloading 61300 entries for movie\n",
      "Finished downloading 61400 entries for movie\n",
      "Finished downloading 61500 entries for movie\n",
      "Finished downloading 61600 entries for movie\n",
      "Finished downloading 61700 entries for movie\n",
      "Finished downloading 61800 entries for movie\n",
      "Finished downloading 61900 entries for movie\n",
      "Finished downloading 62000 entries for movie\n",
      "Finished downloading 62100 entries for movie\n",
      "Finished downloading 62200 entries for movie\n",
      "Finished downloading 62300 entries for movie\n",
      "Finished downloading 62400 entries for movie\n",
      "Finished downloading 62500 entries for movie\n",
      "Finished downloading 62600 entries for movie\n",
      "Finished downloading 62700 entries for movie\n",
      "Finished downloading 62800 entries for movie\n",
      "Finished downloading 62900 entries for movie\n",
      "Finished downloading 63000 entries for movie\n",
      "Finished downloading 63100 entries for movie\n",
      "Finished downloading 63200 entries for movie\n",
      "Finished downloading 63300 entries for movie\n",
      "Finished downloading 63400 entries for movie\n",
      "Finished downloading 63500 entries for movie\n",
      "Finished downloading 63600 entries for movie\n",
      "Finished downloading 63700 entries for movie\n",
      "Finished downloading 63800 entries for movie\n",
      "Finished downloading 63900 entries for movie\n",
      "Finished downloading 64000 entries for movie\n",
      "Finished downloading 64100 entries for movie\n",
      "Finished downloading 64200 entries for movie\n",
      "Finished downloading 64300 entries for movie\n",
      "Finished downloading 64400 entries for movie\n",
      "Finished downloading 64500 entries for movie\n",
      "Finished downloading 64600 entries for movie\n",
      "Finished downloading 64700 entries for movie\n",
      "Finished downloading 64800 entries for movie\n",
      "Finished downloading 64900 entries for movie\n",
      "Finished downloading 65000 entries for movie\n",
      "Finished downloading 65100 entries for movie\n",
      "Finished downloading 65200 entries for movie\n",
      "Finished downloading 65300 entries for movie\n",
      "Finished downloading 65400 entries for movie\n",
      "Finished downloading 65500 entries for movie\n",
      "Finished downloading 65600 entries for movie\n",
      "Finished downloading 65700 entries for movie\n",
      "Finished downloading 65800 entries for movie\n",
      "Finished downloading 65900 entries for movie\n",
      "Finished downloading 66000 entries for movie\n",
      "Finished downloading 66100 entries for movie\n",
      "Finished downloading 66200 entries for movie\n",
      "Finished downloading 66300 entries for movie\n",
      "Finished downloading 66400 entries for movie\n",
      "Finished downloading 66500 entries for movie\n",
      "Finished downloading 66600 entries for movie\n",
      "Finished downloading 66700 entries for movie\n",
      "Finished downloading 66800 entries for movie\n",
      "Finished downloading 66900 entries for movie\n",
      "Finished downloading 67000 entries for movie\n",
      "Finished downloading 67100 entries for movie\n",
      "Finished downloading 67200 entries for movie\n",
      "Finished downloading 67300 entries for movie\n",
      "Finished downloading 67400 entries for movie\n",
      "Finished downloading 67500 entries for movie\n",
      "Finished downloading 67600 entries for movie\n",
      "Finished downloading 67700 entries for movie\n",
      "Finished downloading 67800 entries for movie\n",
      "Finished downloading 67900 entries for movie\n",
      "Finished downloading 68000 entries for movie\n",
      "Finished downloading 68100 entries for movie\n",
      "Finished downloading 68200 entries for movie\n",
      "Finished downloading 68300 entries for movie\n",
      "Finished downloading 68400 entries for movie\n",
      "Finished downloading 68500 entries for movie\n",
      "Finished downloading 68600 entries for movie\n",
      "Finished downloading 68700 entries for movie\n",
      "Finished downloading 68800 entries for movie\n",
      "Finished downloading 68900 entries for movie\n",
      "Finished downloading 69000 entries for movie\n",
      "Finished downloading 69100 entries for movie\n",
      "Finished downloading 69200 entries for movie\n",
      "Finished downloading 69300 entries for movie\n",
      "Finished downloading 69400 entries for movie\n",
      "Finished downloading 69500 entries for movie\n",
      "Finished downloading 69600 entries for movie\n",
      "Finished downloading 69700 entries for movie\n",
      "Finished downloading 69800 entries for movie\n",
      "Finished downloading 69900 entries for movie\n",
      "Finished downloading 70000 entries for movie\n",
      "Finished downloading 70100 entries for movie\n",
      "Finished downloading 70200 entries for movie\n",
      "Finished downloading 70300 entries for movie\n",
      "Finished downloading 70400 entries for movie\n",
      "Finished downloading 70500 entries for movie\n",
      "Finished downloading 70600 entries for movie\n",
      "Finished downloading 70700 entries for movie\n",
      "Finished downloading 70800 entries for movie\n",
      "Finished downloading 70900 entries for movie\n",
      "Finished downloading 71000 entries for movie\n",
      "Finished downloading 71100 entries for movie\n",
      "Finished downloading 71200 entries for movie\n",
      "Finished downloading 71300 entries for movie\n",
      "Finished downloading 71400 entries for movie\n",
      "Finished downloading 71500 entries for movie\n",
      "Finished downloading 71600 entries for movie\n",
      "Finished downloading 71700 entries for movie\n",
      "Finished downloading 71800 entries for movie\n",
      "Finished downloading 71900 entries for movie\n",
      "Finished downloading 72000 entries for movie\n",
      "Finished downloading 72100 entries for movie\n",
      "Finished downloading 72200 entries for movie\n",
      "Finished downloading 72300 entries for movie\n",
      "Finished downloading 72400 entries for movie\n",
      "Finished downloading 72500 entries for movie\n",
      "Finished downloading 72600 entries for movie\n",
      "Finished downloading 72700 entries for movie\n",
      "Finished downloading 72800 entries for movie\n",
      "Finished downloading 72900 entries for movie\n",
      "Finished downloading 73000 entries for movie\n",
      "Finished downloading 73100 entries for movie\n",
      "Finished downloading 73200 entries for movie\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished downloading 73300 entries for movie\n",
      "Finished downloading 73400 entries for movie\n",
      "Finished downloading 73500 entries for movie\n",
      "Finished downloading 73600 entries for movie\n",
      "Finished downloading 73700 entries for movie\n",
      "Finished downloading 73800 entries for movie\n",
      "Finished downloading 73900 entries for movie\n",
      "Finished downloading 74000 entries for movie\n",
      "Finished downloading 74100 entries for movie\n",
      "Finished downloading 74200 entries for movie\n",
      "Finished downloading 74300 entries for movie\n",
      "Finished downloading 74400 entries for movie\n",
      "Finished downloading 74500 entries for movie\n",
      "Finished downloading 74600 entries for movie\n",
      "Finished downloading 74700 entries for movie\n",
      "Finished downloading 74800 entries for movie\n",
      "Finished downloading 74900 entries for movie\n",
      "Finished downloading 75000 entries for movie\n",
      "Finished downloading 75100 entries for movie\n",
      "Finished downloading 75200 entries for movie\n",
      "Finished downloading 75300 entries for movie\n",
      "Finished downloading 75400 entries for movie\n",
      "Finished downloading 75500 entries for movie\n",
      "Finished downloading 75600 entries for movie\n",
      "Finished downloading 75700 entries for movie\n",
      "Finished downloading 75800 entries for movie\n",
      "Finished downloading 75900 entries for movie\n",
      "Finished downloading 76000 entries for movie\n",
      "Finished downloading 76100 entries for movie\n",
      "Finished downloading 76200 entries for movie\n",
      "Finished downloading 76300 entries for movie\n",
      "Finished downloading 76400 entries for movie\n",
      "Finished downloading 76500 entries for movie\n",
      "Finished downloading 76600 entries for movie\n",
      "Finished downloading 76700 entries for movie\n",
      "Finished downloading 76800 entries for movie\n",
      "Finished downloading 76900 entries for movie\n",
      "Finished downloading 77000 entries for movie\n",
      "Finished downloading 77100 entries for movie\n",
      "Finished downloading 77200 entries for movie\n",
      "Finished downloading 77300 entries for movie\n",
      "Finished downloading 77400 entries for movie\n",
      "Finished downloading 77500 entries for movie\n",
      "Finished downloading 77600 entries for movie\n",
      "Finished downloading 77700 entries for movie\n",
      "Finished downloading 77800 entries for movie\n",
      "Finished downloading 77900 entries for movie\n",
      "Finished downloading 78000 entries for movie\n",
      "Finished downloading 78100 entries for movie\n",
      "Finished downloading 78200 entries for movie\n",
      "Finished downloading 78300 entries for movie\n",
      "Finished downloading 78400 entries for movie\n",
      "Finished downloading 78500 entries for movie\n",
      "Finished downloading 78600 entries for movie\n",
      "Finished downloading 78700 entries for movie\n",
      "Finished downloading 78800 entries for movie\n",
      "Finished downloading 78900 entries for movie\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-f9d71fbddf82>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m    170\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0m__name__\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'__main__'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    171\u001b[0m     \u001b[0mAPI_KEY\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'329c476474145bc1797f3f323d74e654'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 172\u001b[0;31m     \u001b[0mdownload_all_data\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-2-f9d71fbddf82>\u001b[0m in \u001b[0;36mdownload_all_data\u001b[0;34m()\u001b[0m\n\u001b[1;32m    165\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mdownload_all_data\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    166\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mcategory\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mCATEGORIES\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 167\u001b[0;31m         \u001b[0mdownload_ids\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcategory\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mload_id_list\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcategory\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    168\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    169\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-2-f9d71fbddf82>\u001b[0m in \u001b[0;36mdownload_ids\u001b[0;34m(category, id_list)\u001b[0m\n\u001b[1;32m    150\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf'Downloading details for {category}'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    151\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mmovie_id\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mid_list\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 152\u001b[0;31m         \u001b[0mcurrent_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmake_detail_request\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcategory\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmovie_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    153\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mcurrent_data\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    154\u001b[0m             \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf'Failed on id # {movie_id}'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-2-f9d71fbddf82>\u001b[0m in \u001b[0;36mmake_detail_request\u001b[0;34m(category, entry_id)\u001b[0m\n\u001b[1;32m     63\u001b[0m         \u001b[0mcategory_specifics\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcategory_specifics\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     64\u001b[0m                                     )\n\u001b[0;32m---> 65\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mmake_request\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcall_url\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     66\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     67\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m<ipython-input-2-f9d71fbddf82>\u001b[0m in \u001b[0;36mmake_request\u001b[0;34m(call_url, prior_attempts)\u001b[0m\n\u001b[1;32m     45\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mwas_rate_limited\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresponse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     46\u001b[0m         \u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mRATE_LIMITER_DELAY_SECONDS\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 47\u001b[0;31m     \u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mMAX_DOWNLOADS_PER_SECOND\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     48\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mwas_successful\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresponse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     49\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjson\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "BASE_API_CALL = 'https://api.themoviedb.org/3/{category}/{entry_id}?api_key={api_key}{category_specifics}'\n",
    "CATEGORIES = ['movie']\n",
    "DOWNLOADS_PER_DISK_WRITE = 100\n",
    "MAX_DOWNLOADS_PER_SECOND = 7\n",
    "MAX_ATTEMPTS = 3\n",
    "RATE_LIMITER_DELAY_SECONDS = 20\n",
    "RATE_LIMIT_EXCEEDED_STATUS_CODE = 429\n",
    "SUCCESSFUL_CALL_STATUS_CODE = 200\n",
    "\n",
    "CATEGORY_SPECIFIC_CALLS = {\n",
    "    'movie': '&append_to_response=credits,keywords',\n",
    "                            }\n",
    "\n",
    "JSON_COLUMNS = {\n",
    "    'genres',\n",
    "    'keywords',\n",
    "    'production_countries',\n",
    "    'production_companies',\n",
    "    'spoken_languages'\n",
    "                }\n",
    "\n",
    "KEYS_TO_DROP = {\n",
    "    'adult',\n",
    "    'backdrop_path',\n",
    "    'belongs_to_collection',\n",
    "    'imdb_id',\n",
    "    'poster_path',\n",
    "    'profile_path',\n",
    "    'video',\n",
    "                }\n",
    "\n",
    "\n",
    "def was_successful(response):\n",
    "    return response.status_code == SUCCESSFUL_CALL_STATUS_CODE\n",
    "\n",
    "\n",
    "def was_rate_limited(response):\n",
    "    return response.status_code == RATE_LIMIT_EXCEEDED_STATUS_CODE\n",
    "\n",
    "\n",
    "def make_request(call_url, prior_attempts=0):\n",
    "    if prior_attempts >= MAX_ATTEMPTS:\n",
    "        return None\n",
    "    response = requests.get(call_url)\n",
    "    if was_rate_limited(response):\n",
    "        sleep(RATE_LIMITER_DELAY_SECONDS)\n",
    "    sleep(1 / MAX_DOWNLOADS_PER_SECOND)\n",
    "    if was_successful(response):\n",
    "        return response.json()\n",
    "    else:\n",
    "        sleep(1)\n",
    "        return make_request(call_url, prior_attempts + 1)\n",
    "\n",
    "\n",
    "def make_detail_request(category, entry_id):\n",
    "    category_specifics = ''\n",
    "    if category in CATEGORY_SPECIFIC_CALLS:\n",
    "        category_specifics = CATEGORY_SPECIFIC_CALLS[category]\n",
    "    call_url = BASE_API_CALL.format(\n",
    "        category=category,\n",
    "        entry_id=entry_id,\n",
    "        api_key=API_KEY,\n",
    "        category_specifics=category_specifics,\n",
    "                                    )\n",
    "    return make_request(call_url)\n",
    "\n",
    "\n",
    "def make_category_id_url_suffix(category, extension='json'):\n",
    "    year = str(pd.datetime.today().year)\n",
    "    month = str(pd.datetime.today().month).zfill(2)\n",
    "    day = str(pd.datetime.today().day - 1).zfill(2)\n",
    "    return '_'.join([category, 'ids', month, day, year]) + '.' + extension\n",
    "\n",
    "\n",
    "def download_id_list_as_csv(category):\n",
    "    print(f'Downloading list of ids for {category}')\n",
    "    id_list_name = make_category_id_url_suffix(category)\n",
    "    ID_LISTS_RAW_URL = 'http://files.tmdb.org/p/exports/{0}.gz'.format(id_list_name)\n",
    "    with gzip.open(BytesIO(requests.get(ID_LISTS_RAW_URL).content), 'r') as f_open:\n",
    "        id_list = f_open.readlines().decode('utf-8')\n",
    "    # original 'json' is malformed, is actually one dict per line\n",
    "    ids = pd.DataFrame([json.loads(x) for x in id_list])\n",
    "    # some entries in the movie id list appear to be collections rather than movies\n",
    "    if 'original_title' in ids.columns:\n",
    "        ids.original_title = ids.original_title.apply(str)\n",
    "        ids = ids[~ids.original_title.str.endswith(' Collection')].copy()\n",
    "\n",
    "\n",
    "def load_id_list(category):\n",
    "    if not os.path.exists(category + '_ids.csv'):\n",
    "        download_id_list_as_csv(category)\n",
    "    df = pd.read_csv(category + '_ids.csv')\n",
    "    return df.id.values.tolist()\n",
    "\n",
    "\n",
    "def unpack_credits(df):\n",
    "    credits = pd.DataFrame(df[['credits', 'id', 'title']])\n",
    "    credits.rename(columns={'id': 'movie_id'}, inplace=True)\n",
    "    new_columns = ['cast', 'crew']\n",
    "    for column in new_columns:\n",
    "        credits[column] = credits['credits'].apply(\n",
    "            lambda x: x[column] if column in x else [])\n",
    "        credits[column] = credits[column].apply(lambda x:\n",
    "            [{k: v for k, v in i.items() if k not in {'profile_path'}} for i in x])\n",
    "        credits[column] = credits[column].apply(json.dumps)\n",
    "    del credits['credits']\n",
    "    del df['credits']\n",
    "    return df, credits\n",
    "\n",
    "\n",
    "def export_data(category, all_entries):\n",
    "    if not all_entries:\n",
    "        return None\n",
    "    df = pd.DataFrame(all_entries)\n",
    "    df = df[[x for x in df.columns if x not in KEYS_TO_DROP]].copy()\n",
    "    if len(df[df.id.isnull()]) > 0:\n",
    "        print(f'Dropping {len(df[df.id.isnull()])} entries without ids')\n",
    "        df = df[~df.id.isnull()]\n",
    "    df = df[df.id.apply(lambda x: str(x).isnumeric())]\n",
    "    # this section about credits is specific to the movie category\n",
    "    df, credits = unpack_credits(df)\n",
    "    df['keywords'] = df['keywords'].apply(lambda x:\n",
    "        x['keywords'] if 'keywords' in x else [])\n",
    "    for column in JSON_COLUMNS:\n",
    "        df[column] = df[column].apply(json.dumps)\n",
    "    needs_header = not(os.path.exists(category + '_data.csv'))\n",
    "    df.to_csv(category + '_data.csv', index=False, mode='a+', header=needs_header)\n",
    "    credits.to_csv(category + '_credits.csv', index=False, mode='a+', header=needs_header)\n",
    "\n",
    "\n",
    "def download_ids(category, id_list):\n",
    "    if os.path.exists(category + '_data.csv'):\n",
    "        existing_ids = pd.read_csv(category + '_data.csv', usecols=['id'], dtype=object)\n",
    "        set(existing_ids.id.values.tolist())\n",
    "        id_list = [x for x in id_list if str(x) not in existing_ids]\n",
    "    counter = 0\n",
    "    all_entries = []\n",
    "    print(f'Downloading details for {category}')\n",
    "    for movie_id in id_list:\n",
    "        current_data = make_detail_request(category, movie_id)\n",
    "        if not current_data:\n",
    "            print(f'Failed on id # {movie_id}')\n",
    "            continue\n",
    "        counter += 1\n",
    "        all_entries.append(current_data)\n",
    "        if counter % DOWNLOADS_PER_DISK_WRITE == 0:\n",
    "            print(f'Finished downloading {counter} entries for {category}')\n",
    "            export_data(category, all_entries)\n",
    "            all_entries = []\n",
    "    export_data(category, all_entries)\n",
    "\n",
    "\n",
    "def download_all_data():\n",
    "    for category in CATEGORIES:\n",
    "        download_ids(category, load_id_list(category))\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    API_KEY = '329c476474145bc1797f3f323d74e654'\n",
    "    download_all_data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f1839695",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
